/*===========drop=================== */
/* 게시판 */
DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

/* 게시판리스트 */
DROP TABLE BOARD_LIST 
	CASCADE CONSTRAINTS;

/* 게시판형식 */
DROP TABLE BOARD_TYPE 
	CASCADE CONSTRAINTS;

/* 카테고리 */
DROP TABLE CATEGORY 
	CASCADE CONSTRAINTS;

/* 답변형게시판 */
DROP TABLE REBOARD 
	CASCADE CONSTRAINTS;

/* 사진게시판 */
DROP TABLE ALBUM 
	CASCADE CONSTRAINTS;

/* 자료실 */
DROP TABLE BBS 
	CASCADE CONSTRAINTS;

/* 메모글 */
DROP TABLE MEMO 
	CASCADE CONSTRAINTS;
	
DROP SEQUENCE BOARD_TYPE_SEQ;

DROP SEQUENCE CATEGORY_CSEQ;

DROP SEQUENCE BOARD_LIST_SEQ;

DROP SEQUENCE BOARD_SEQ;

DROP SEQUENCE REBOARD_RSEQ;

DROP SEQUENCE ALBUM_ASEQ;

DROP SEQUENCE BBS_BSEQ;

DROP SEQUENCE MEMO_MSEQ;

/*============================== */
/* 게시판형식 */
CREATE TABLE BOARD_TYPE (
	BTYPE NUMBER NOT NULL, /* 게시판형식번호 */
	BTYPE_NAME VARCHAR2(100) /* 게시판형식이름 */
);

CREATE UNIQUE INDEX PK_BOARD_TYPE
	ON BOARD_TYPE (
		BTYPE ASC
	);

ALTER TABLE BOARD_TYPE
	ADD
		CONSTRAINT PK_BOARD_TYPE
		PRIMARY KEY (
			BTYPE
		);

COMMENT ON TABLE BOARD_TYPE IS '게시판형식';

COMMENT ON COLUMN BOARD_TYPE.BTYPE IS '게시판형식번호';

COMMENT ON COLUMN BOARD_TYPE.BTYPE_NAME IS '게시판형식이름';

CREATE SEQUENCE BOARD_TYPE_SEQ
START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO BOARD_TYPE (BTYPE, BTYPE_NAME)
VALUES (BOARD_TYPE_SEQ.NEXTVAL, '공지사항');

INSERT INTO BOARD_TYPE (BTYPE, BTYPE_NAME)
VALUES (BOARD_TYPE_SEQ.NEXTVAL, '방명록');

INSERT INTO BOARD_TYPE (BTYPE, BTYPE_NAME)
VALUES (BOARD_TYPE_SEQ.NEXTVAL, '한줄게시판');

INSERT INTO BOARD_TYPE (BTYPE, BTYPE_NAME)
VALUES (BOARD_TYPE_SEQ.NEXTVAL, '일반게시판');

INSERT INTO BOARD_TYPE (BTYPE, BTYPE_NAME)
VALUES (BOARD_TYPE_SEQ.NEXTVAL, '답변게시판');

INSERT INTO BOARD_TYPE (BTYPE, BTYPE_NAME)
VALUES (BOARD_TYPE_SEQ.NEXTVAL, '앨범게시판');

INSERT INTO BOARD_TYPE (BTYPE, BTYPE_NAME)
VALUES (BOARD_TYPE_SEQ.NEXTVAL, '자료실');

COMMIT;

/*=================================== 카테고리 */
CREATE TABLE CATEGORY (
	CCODE NUMBER NOT NULL, /* 카테고리번호 */
	CNAME VARCHAR2(100) /* 카테고리이름 */
);

CREATE UNIQUE INDEX PK_CATEGORY
	ON CATEGORY (
		CCODE ASC
	);

ALTER TABLE CATEGORY
	ADD
		CONSTRAINT PK_CATEGORY
		PRIMARY KEY (
			CCODE
		);

COMMENT ON TABLE CATEGORY IS '카테고리';

COMMENT ON COLUMN CATEGORY.CCODE IS '카테고리번호';

COMMENT ON COLUMN CATEGORY.CNAME IS '카테고리이름';

CREATE SEQUENCE CATEGORY_CSEQ
START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO CATEGORY (CCODE, CNAME)
VALUES(CATEGORY_CSEQ.NEXTVAL, '공지사항');

INSERT INTO CATEGORY (CCODE, CNAME)
VALUES(CATEGORY_CSEQ.NEXTVAL, '보도자료');

INSERT INTO CATEGORY (CCODE, CNAME)
VALUES(CATEGORY_CSEQ.NEXTVAL, '게시판'); 

