/* 답변형게시판 */
SELECT * FROM REBOARD;

DROP TABLE REBOARD; 


CREATE TABLE REBOARD (
	RSEQ NUMBER NOT NULL, /* 답변게시판번호 */
	SEQ NUMBER, /* 글번호 */
	REF NUMBER, /* 그룹번호 */
	LEV NUMBER, /* 들여쓰기 */
	STEP NUMBER, /* 답변정렬 */
	PSEQ NUMBER, /* 원글번호 */
	REPLY NUMBER DEFAULT 0 /* 답변갯수 */
);

CREATE UNIQUE INDEX PK_REBOARD
	ON REBOARD (
		RSEQ ASC
	);

ALTER TABLE REBOARD
	ADD
		CONSTRAINT PK_REBOARD
		PRIMARY KEY (
			RSEQ
		);

COMMENT ON TABLE REBOARD IS '답변형게시판';

COMMENT ON COLUMN REBOARD.RSEQ IS '답변게시판번호';

COMMENT ON COLUMN REBOARD.SEQ IS '글번호';

COMMENT ON COLUMN REBOARD.REF IS '그룹번호';

COMMENT ON COLUMN REBOARD.LEV IS '들여쓰기';

COMMENT ON COLUMN REBOARD.STEP IS '답변정렬';

COMMENT ON COLUMN REBOARD.PSEQ IS '원글번호';

COMMENT ON COLUMN REBOARD.REPLY IS '답변갯수';

CREATE SEQUENCE REBOARD_RSEQ
START WITH 1 INCREMENT BY 1 NOCACHE;


select * from user_sequences;